#pragma once

#define ENABLE_LOGGING
#ifdef ENABLE_LOGGING
    #define ENABLE_CONSOLE_OUTPUT
#endif

#define STATIC_LOAD_AUTOSTART

#define FEATURE_THREADS_FILTER
#define FEATURE_DLL_FILTER
#define FEATURE_MEMORY_FILTER
#define FEATURE_STACKTRACE_CHECK

#if defined FEATURE_DLL_FILTER && defined FEATURE_STACKTRACE_CHECK
    #define FEATURE_WINDOWS_HOOKS_FILTER
    #ifdef FEATURE_WINDOWS_HOOKS_FILTER
        #define FEATURE_ALLOW_SYSTEM_MODULES
    #endif
#endif